### ISSUE TITLE
var y, should it not then say y = 4 * Pi ?

### ISSUE THREAD

**Issue by Suz4nne** [initpy/go-book#33]
page = http://go-book.appspot.com/first.html

In the section called "What is a constant?"   the example says
 "var y float32
x = 4 \* Pi 
//when compiled, y == 4 \* 3.14"

At first I thought my programming was just terribly terribly rusty, so asked even geekier husband and he also thinks in my humble opinion that the x really should be a y???

ps love the tutorial

**Comment by initpy** [comment]
Your programming wasn't rusty at all, Suz4nne! My eyes were  ;)
Thank you for noticing this and notifying me, and for your kind words about this humble work!
