### ISSUE TITLE
I'm afraid something happened to the author - he has not been online for 4 years on any of his resources

### ISSUE THREAD

**Issue by bakirov** [initpy/go-book#66]
Dear all!

I'm afraid something happened to the author - he is not been online for 4 years on any his resources. Let's hope, everything is OK with him.
Meanwhile, anyone wills to step in and continue maintaining this book, so we can continue on a new fork and try to complete this book?

**Comment by bakirov** [comment]
I emailed him at init.py@gmail.com - let's see, if we'll get an answer.

**Comment by smartexpert** [comment]
Did you get a response?
I only read one chapter from the book and it's by far the easiest to follow compared to other resources I'm cramming. The author is gifted, I'm really interested in seeing more of their work.

**Comment by bakirov** [comment]
@smartexpert , unfortunately I did not get any response, so I'm afraid something serious happened.

**Comment by xiaopeng163** [comment]
Good luck to him.  I think someone can fork and maintain a new repo and make an announce here.

**Comment by ugjka** [comment]
This is a bummer, this is a really good book :(

**Comment by aleksarias** [comment]
This is an awesome book.

**Comment by hmbrg** [comment]
Has there been any response?

**Comment by bakirov** [comment]
@brighthero , no, unfortunately, no response. And I'm closing this ticket.
